"""End-to-end batch pipeline.

  python scripts/run_pipeline.py --synthetic          # ingest -> panel -> fusion + LOSO
  python scripts/run_pipeline.py --synthetic --full   # ...then detect -> attribute -> eval
  python scripts/run_pipeline.py                      # live APIs where keys exist

--full exists because the outputs are a CHAIN, and a half-run chain lies. Running
only the fusion stage leaves a stale hotspots.json and attributions.json on disk
from a previous world — the API serves them happily, the map renders them, and
nothing anywhere says they no longer correspond to the panel underneath. That
bit us once already. If you regenerate the panel, regenerate what reads it.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from ingestion.collectors.pollers import run as ingest_run
from ingestion.preprocessing.panel import build_panel
from intelligence.models.fusion import run as fusion_run

RULE = "=" * 62


def main():
    argv = sys.argv[1:]
    synthetic = "--synthetic" in argv
    full = "--full" in argv

    print(RULE)
    ingest_run(synthetic=synthetic)
    print(RULE)
    build_panel()
    print(RULE)
    fusion_run()

    if not full:
        print(RULE)
        print("Fusion stage complete: data/outputs/{panel,fusion_field}.parquet + loso.json")
        print("NOTE: hotspots.json / attributions.json are NOT regenerated by this run and")
        print("      may be stale. Re-run with --full, or run detect.py + attribution.py.")
        return

    # Imported here, not at module top: these read data/outputs/panel.parquet at
    # import time via the ward layer, which does not exist on a cold checkout.
    from intelligence.agents.detect import detect
    from intelligence.agents.attribution import run as attribute_run

    print(RULE)
    detect()
    print(RULE)
    attribute_run()
    print(RULE)
    print("Full pipeline complete. Evaluate with:")
    print("  python scripts/eval_detection.py     # the headline stat: sources found vs missed")
    print("  python scripts/eval_attribution.py   # attribution accuracy + confidence calibration")
    print("  python scripts/eval_hotspot_recovery.py  # fusion as an EXPOSURE map")


if __name__ == "__main__":
    main()
